spring:
  datasource:
    url: jdbc:postgresql://db:5432/slideshow_db  # Змінив localhost на db (ім'я сервісу в docker-compose.yml)
    username: postgres
    password: mysecretpassword
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        show_sql: false
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.xml
  kafka:
    producer:
      bootstrap-servers: kafka:9092  # Змінив localhost на kafka (ім'я сервісу в docker-compose.yml)
      key-serializer: org.apache.kafka.common.serialization.LongSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      bootstrap-servers: kafka:9092  # Додав для споживача
      group-id: slideshow-consumer-group  # Додав групу споживачів
      key-deserializer: org.apache.kafka.common.serialization.LongDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
  codec:
    max-in-memory-size: 10MB
server:
  port: 8080
app:
  kafka:
    topic: api-actions