spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/slideshow_db
    username: postgres
    password: mysecretpassword
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        show_sql: false
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.xml
server:
  port: 8080